version: '3.1'

services:

  questions_postgres_db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      -  questions-db-data:/var/lib/postgresql/data/
      - ./data/db_data:/app
    environment:
      POSTGRES_USER: farit_priglasil
      POSTGRES_PASSWORD: f4r17_pr1gl451l
      POSTGRES_DB: questions
  context_redis_db:
    image: redis
    ports:
      - "6379:6379"
  indexer:
    build: ./indexer
    volumes:
      - ./data/rubert_cased_L-12_H-768_A-12_v1:/indexer/rubert_cased_L-12_H-768_A-12_v1
    links:
      - "questions_postgres_db"
      - "context_redis_db"
    ports:
      - "8125:8125"
  python-app:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: farit_priglasil
      POSTGRES_PASSWORD: f4r17_pr1gl451l
      POSTGRES_DB: questions
    links:
      - "questions_postgres_db"
      - "context_redis_db"
      - "indexer"
  telegram_bot:
    build: ./telegram_bot
    environment:
      SECRET: tg_secret_key
    links:
      - "python-app"

volumes:
  questions-db-data:
